In [1]:
from tf_sentence_transformers import SentenceTransformer

demo_model = SentenceTransformer.from_pretrained('uer/sbert-base-chinese-nli', from_pt=True)

2023-10-13 17:37:53.569334: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/hanshen/work/.venv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-10-13 17:38:32.362288: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some weights of the PyTorch model were not used when init

In [2]:
import tensorflow as tf

In [3]:
tf.constant([["你吃了吗"]])

<tf.Tensor: shape=(1, 1), dtype=string, numpy=
array([[b'\xe4\xbd\xa0\xe5\x90\x83\xe4\xba\x86\xe5\x90\x97']],
      dtype=object)>

In [4]:
a = demo_model(tf.constant([["你吃了吗"], ["我还没吃"]]))

In [5]:
a

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.02267614, -0.01021547,  0.01628796, ..., -0.05491208,
         0.0209373 , -0.03513766],
       [-0.02790518, -0.0041753 ,  0.0141114 , ...,  0.00288682,
        -0.0209191 , -0.04053693]], dtype=float32)>

In [9]:
len(a.numpy().tolist())

2